name: Linter

on:
  pull_request:

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            eslint:
              - '**.js,**.jsx,**.ts,**.tsx'
            stylelint:
              - '**.css'

  eslint:
    name: ESLint
    needs: check-changes
    if: needs.changes.outputs.eslint == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node Packages
        uses: ./.github/actions/install-node-packages

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
